version: '3'

services:
  health-status-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: padminisys/health-status:dev
    ports:
      - '3001:3000'
