apiVersion: v1
kind: Pod
metadata:
  namespace: devops-tools
spec:
  serviceAccountName: jenkins-admin
  containers:
    - name: helm
      image: docker.io/alpine/helm:3.11.2
      command:
        - sleep
      args:
        - 9999999
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 9999999
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
