version: '3'

services:
  health-status-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: padminisys/health-status:prod
    ports:
      - '3003:3000'
